// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
)

// Injectors from wire.go:

func initApp() (*kratos.App, func(), error) {
	app := newApp()
	return app, func() {
	}, nil
}
